version: "3.4"

services:

  jenkins:
    image: jenkins-ci
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./old_jenkins:/var/jenkins_home
      - /var/tmp/docker:/var/jenkins_home/workspace/build_idwell/web/test_results
